### ISSUE TITLE
Add player account endpoint

### ISSUE THREAD

**Issue by fulvius31** [fulvius31/Polyglot#1]
One of the requirement of Polyglot is to track the players scores. 

- [x] So we need to create an entity `Player` with at least the following attributes : 

- `username`
- `email`
- `password (enc)`
- `scores`

Then we need at least two endpoints to create and get an user :

- [x] a `GET` endpoint `$BASE_URL/signin` that takes a `json` as an input with `username, password` and return a `json` as output. This output contains at least the attribute `errorCode` (we will talk about tokens later).

The attribute `errorCode` could be:

- `10200` for the success case (email and password correct)
- `10404` user not found or wrong password
- `10001` generic error

- [x] a `POST` endpoint `$BASE_URL/signup` that takes a `json` as an input with `email, password` and return a `json` as output. This output contains at least the attribute `errorCode`.

- `10200` for the success case (user was successfully created)
- `10404` user already exists
- `10001` generic error

**Comment by Sandeep-1-Kumar** [comment]
> One of the requirement of Polyglot is to track the players scores.
> 
> * [x]  So we need to create an entity `Player` with at least the following attributes :
> * `username`
> * `email`
> * `password (enc)`
> * `scores`
 ------------------> Entity creates as per the discussion

> Then we need at least two endpoints to create and get an user :
> 
> * [ ]  a `GET` endpoint `$BASE_URL/signin` that takes a `json` as an input with `username, password` and return a `json` as output. This output contains at least the attribute `errorCode` (we will talk about tokens later).
> 
> The attribute `errorCode` could be:
> 
> * `10200` for the success case (email and password correct)
> * `10404` user not found or wrong password
> * `10001` generic error
------->
local URL: http://localhost:8080/polyglot/player/signIn
Base path : polyglot/player
endpoint : /signIn


Backend request body for sign In : 

{
    "userName": "sandy@gmail.com",
    "password": "San@1234"
}


Back end response body : 
{
    "email": "sandy@gmail.com",
    "name": "Sandy",
    "score": "0",
    "errorCode": "10200",
    "errorMessage": "Player sucessfully validated"
}

> * [ ]  a `POST` endpoint `$BASE_URL/signup` that takes a `json` as an input with `email, password` and return a `json` as output. This output contains at least the attribute `errorCode`.
> * `10200` for the success case (user was successfully created)
> * `10404` user already exists
> * `10001` generic error

post URL : 
http://localhost:8080/polyglot/player/signUp
end point : signUp
Request body :

{
    "email": "muru@gmail.com",
    "password": "Murug@123",
    "name" : "Murugan"
}
Response body : 
{
    "email": "muru@gmail.com",
    "name": "Murugan",
    "score": "0",
    "errorCode": "10200",
    "errorMessage": "User sucessfully created"
}

error cases :
sign in /
{
    "email": null,
    "name": null,
    "score": null,
    "errorCode": "10404",
    "errorMessage": "please check the login credentials"
}
 

sign up/
{
    "email": null,
    "name": null,
    "score": null,
    "errorCode": "10404",
    "errorMessage": "user already exsists"
}

Exceptions handled in : 
10404 - code and 
error message
