### ISSUE TITLE
Home page Language Selection

### ISSUE THREAD

**Issue by Sandeep-1-Kumar** [fulvius31/Polyglot#21]
The URL to get the languages details from home page : http://localhost:8080/polyglot/player/home

Response json : /Available languages to learn in a json format/
{
"0" : "Italian",
"1" : "French",
"2" : "Spanish" 
}
Based on the details home page UI will have details to display

**Comment by fulvius31** [comment]
I would change the link into `http://localhost:8080/polyglot/getLanguages`

Then, our `$BASE_URL` would be : `http(s)://domain.com:8080/polyglot`

So the endpoint is `/getLanguages`

and I would change the Json response in, because they key in the json has to be representative :

```
{
  "languages": [
    {
      "language_name": "Italian"
    },
    {
      "language_name": "French"
    },
    {
      "language_name": "Spanish",
    }
  ]
}
```

**Comment by fulvius31** [comment]
We can also add our custom code for every countries : starting from a `BASE_CODE = 2000` we can have

```
{
  "languages": [
    {
      "language_name": "Italian",
      "language_code": 2001
    },
    {
      "language_name": "French",
      "language_code": 2002
    },
    {
      "language_name": "Spanish",
      "language_code": 2003
    }
  ]
}
```

**Comment by Sandeep-1-Kumar** [comment]
Yes Alessandro thanks for the sugesstion and i have done the hompage implementation these are test samples:

http://localhost:8080/polyglot/getLanguages

{
    "languages": [
        {
            "languageCode": "2001",
            "languageName": "Italian"
        },
        {
            "languageCode": "2002",
            "languageName": "Spanish"
        }
    ]
}

I have updated the whole functionality and will raise a pull request for review
