### ISSUE TITLE
Dashboard Details

### ISSUE THREAD

**Issue by Sandeep-1-Kumar** [fulvius31/Polyglot#24]
http://localhost:8080/polyglot/player/getLanguageScores?email=sandy@gmail.com&languageName=Spanish
Response json :
 {
    "learning_1": 0,
    "learning_2": 0,
    "learning_3": 0,
    "activity_3": 0,
    "activity_2": 0,
    "activity_1": 0
}

I request front end coordinators to update the dashboard UI using above details

**Comment by fulvius31** [comment]
Great job.

Maybe it could be more descriptive and more maintanable have a Json like this:

``` json
{
  "learning_1": {
    "score": 85
  },
  "learning_2": {
    "score": 72
  },
  "learning_3": {
    "score": 94
  },
  "activity_1": {
    "score": 63
  },
  "activity_2": {
    "score": 78
  },
  "activity_3": {
    "score": 88
  }
}

```
Also, since in the other APIs we are using parameters in a JSON, maybe it could be better if we don't use the parameters in the URL itself. Instead we should use those parameters inside a body in a JSON form.

Let me know what you think

**Comment by Sandeep-1-Kumar** [comment]
Thanks for the suggestion and updates on top of it.

URL: http://localhost:8080/polyglot/player/getLanguageScores
RequestBody:
{
        "email" : "sandy@gmail.com",
        "languageName" : "Spanish"
}
ResponseBody:
{
    "learning_1": {
        "Score": 0
    },
    "learning_2": {
        "Score": 0
    },
    "learning_3": {
        "Score": 0
    },
    "activity_3": {
        "Score": 0
    },
    "activity_2": {
        "Score": 0
    },
    "activity_1": {
        "Score": 0
    }
}
//This case can be neglected because as the player is propagating from home page. 
Error Response: {}

**Comment by fulvius31** [comment]
👌

**Comment by Sandeep-1-Kumar** [comment]
Change i request body : 
{
        "email" : "sandy@gmail.com",
        "languageId" : 2001
}

**Comment by mepripri** [comment]
@Sandeep-1-Kumar , I have integrated the code with Front end everything is working fine :) in the Dashboard.

**Comment by Sandeep-1-Kumar** [comment]
Issue completed.
