### ISSUE TITLE
Home page functionality -2

### ISSUE THREAD

**Issue by Sandeep-1-Kumar** [fulvius31/Polyglot#25]
So lets think about what after retrieving the available languages.

Player should able to choose one . So if he chooses we will assign the language to the player and initialize every module(6) score to 0.

To do that URL : http://localhost:8080/polyglot/player/assignLanguage

RequestBody : 
{
        "email" : "sandy@gmail.com",
        "languageName" : "Italian"
} 
ResposneBody:
{
    "errorCode": "10201",
    "errorMessage": "language Selected Successfully"
}
Failure Response:
{
    "errorCode": "10409",
    "errorMessage": "Invalid player or language"
}
Once accomidate in fron end and close the issue.

**Comment by fulvius31** [comment]
It's ok. Instead of languageName we should use languageCode.

**Comment by Sandeep-1-Kumar** [comment]
Actually i am not setting any languageCode on database it is the spring-boot, I am manipulating the id 0,1,2.... to the language code. Any how languageName is also unique on DB so shall we move with above implementation .And for the front end also it will be easy to send the language name as the button represents the text.

**Comment by fulvius31** [comment]
👍

**Comment by Sandeep-1-Kumar** [comment]
I think i got your point @fulvius31 ,I just again reframed the idea and felt that it is good to use language code so i set up the DB to auto increment id from 2001 .... 200n and update the whole functionality.

New Request Body : 
{
        "email" : "sandy@gmail.com",
        "languageId" : 2001
}
other things are same
