### ISSUE TITLE
Updating a module Score

### ISSUE THREAD

**Issue by Sandeep-1-Kumar** [fulvius31/Polyglot#26]
We need to have a service to update the score of a particular module of a language of a player.

So this is the URL: http://localhost:8080/polyglot/player/updateModuleScore
Request body: 
{
        "email" : "sandy@gmail.com",
        "languageId" : 2001,
        "moduleId" : 2,
        "newScore" : 10
}

Response : 
{
    "learning_1": {
        "Score": "10"
    },
    "learning_2": {
        "Score": "0"
    },
    "learning_3": {
        "Score": "0"
    },
    "activity_3": {
        "Score": "0"
    },
    "activity_2": {
        "Score": "0"
    },
    "activity_1": {
        "Score": "10"
    }
}

**Comment by mepripri** [comment]
@Sandeep-1-Kumar , I have integrated the code with Front end, able to update the score. The backend part is fine

**Comment by Sandeep-1-Kumar** [comment]
Cool , Lets close this.

**Comment by Sandeep-1-Kumar** [comment]
issue closed.
