### ISSUE TITLE
Getting Registered Languages of a player

### ISSUE THREAD

**Issue by Sandeep-1-Kumar** [fulvius31/Polyglot#29]
As you people already know , When ever there is a requirement on backend **Sun**deep **Rises**.
Here I am fulfilling the ask from front End by @mepripri ->Making our application look as beautiful as Gujarat.
So here we can see our mate @kishore223 is learning from what we are doing.
I request the man in action @fulvius31 to review and give me sign off.

This method to retrieve what are the languages registered by player : 

URL : http://localhost:8080/polyglot/player/getRegisteredLanguages

Request Body : 
{
        "email" : "sandy@gmail.com"
}

Response:

{
    "RegisteredLanguages": [
        {
            "languageCode": 2001,
            "languageName": "Italian"
        },
        {
            "languageCode": 2002,
            "languageName": "Spanish"
        }
    ]
}

failure Response : 
{
    "RegisteredLanguages": []
}

**Comment by mepripri** [comment]
I have integrated this function with the frontend, I am able to fetch the Registered languages for each user. This can be closed. :)
